### ISSUE TITLE
java.net.SocketException in Deathdusk 2.15

### ISSUE THREAD

**Issue by Hanmingxuan** [KubeJS-Mods/Rhino#31]
[20:33:29] [Render thread/INFO]: Done in 23.01 ms
[20:33:29] [Render thread/INFO]: Loaded common.properties
[20:33:29] [Render thread/INFO]: Rhino properties loaded.
[20:33:39] [Render thread/ERROR]: Failed to remap Rhino to Mojang Mappings:
[20:33:39] [Render thread/INFO]: [STDERR]: java.net.SocketException: ÄãµÄÖ÷»úÖÐµÄÈí¼þÖÐÖ¹ÁËÒ»¸öÒÑ½¨Á¢µÄÁ¬½Ó¡£
[20:33:39] [Render thread/INFO]: [STDERR]: 	at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:325)
[20:33:39] [Render thread/INFO]: [STDERR]: 	at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:350)
[20:33:39] [Render thread/INFO]: [STDERR]: 	at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:803)
[20:33:39] [Render thread/INFO]: [STDERR]: 	at java.base/java.net.Socket$SocketInputStream.read(Socket.java:966)
[20:33:39] [Render thread/INFO]: [STDERR]: 	at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:478)
[20:33:39] [Render thread/INFO]: [STDERR]: 	at java.base/sun.security.ssl.SSLSocketInputRecord.readFully(SSLSocketInputRecord.java:461)
[20:33:39] [Render thread/INFO]: [STDERR]: 	at java.base/sun.security.ssl.SSLSocketInputRecord.decodeInputRecord(SSLSocketInputRecord.java:243)
[20:33:39] [Render thread/INFO]: [STDERR]: 	at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:181)
[20:33:39] [Render thread/INFO]: [STDERR]: 	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:111)
[20:33:39] [Render thread/INFO]: [STDERR]: 	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1500)
[20:33:39] [Render thread/INFO]: [STDERR]: 	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1415)
[20:33:39] [Render thread/INFO]: [STDERR]: 	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:450)
[20:33:39] [Render thread/INFO]: [STDERR]: 	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:421)
[20:33:39] [Render thread/INFO]: [STDERR]: 	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:580)
[20:33:39] [Render thread/INFO]: [STDERR]: 	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:183)
[latest.log](https://github.com/KubeJS-Mods/Rhino/files/9281795/latest.log)

[20:33:39] [Render thread/INFO]: [STDERR]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665)
[20:33:39] [Render thread/INFO]: [STDERR]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
[20:33:39] [Render thread/INFO]: [STDERR]: 	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
[20:33:39] [Render thread/INFO]: [STDERR]: 	at java.base/java.net.URL.openStream(URL.java:1161)
[20:33:39] [Render thread/INFO]: [STDERR]: 	at org.apache.commons.io.IOUtils.toString(IOUtils.java:2953)
[20:33:39] [Render thread/INFO]: [STDERR]: 	at dev.latvian.mods.rhino.mod.util.MinecraftRemapper.fetchMojMapClasses(MinecraftRemapper.java:242)
[20:33:39] [Render thread/INFO]: [STDERR]: 	at dev.latvian.mods.rhino.mod.util.MinecraftRemapper.loadMojMapClasses(MinecraftRemapper.java:192)
[20:33:39] [Render thread/INFO]: [STDERR]: 	at dev.latvian.mods.rhino.mod.util.MinecraftRemapper.<init>(MinecraftRemapper.java:119)
[20:33:39] [Render thread/INFO]: [STDERR]: 	at dev.latvian.mods.rhino.mod.util.fabric.FabricRemapper.<init>(FabricRemapper.java:16)
[20:33:39] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[20:33:39] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[20:33:39] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[20:33:39] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[20:33:39] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[20:33:39] [Render thread/INFO]: [STDERR]: 	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:789)
[20:33:39] [Render thread/INFO]: [STDERR]: 	at java.base/java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:729)
[20:33:39] [Render thread/INFO]: [STDERR]: 	at java.base/java.util.ServiceLoader$3.next(ServiceLoader.java:1403)
[20:33:39] [Render thread/INFO]: [STDERR]: 	at java.base/java.util.ServiceLoader.findFirst(ServiceLoader.java:1812)
[20:33:39] [Render thread/INFO]: [STDERR]: 	at dev.latvian.mods.rhino.mod.util.RemappingHelper.lambda$static$1(RemappingHelper.java:16)
[20:33:39] [Render thread/INFO]: [STDERR]: 	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:183)
[20:33:39] [Render thread/INFO]: [STDERR]: 	at dev.latvian.mods.rhino.mod.util.RemappingHelper.getMinecraftRemapper(RemappingHelper.java:20)
[20:33:39] [Render thread/INFO]: [STDERR]: 	at dev.latvian.mods.rhino.mod.util.RemappingHelper.createModRemapper(RemappingHelper.java:24)
[20:33:39] [Render thread/INFO]: [STDERR]: 	at dev.latvian.mods.kubejs.script.ScriptManager.load(ScriptManager.java:101)
[20:33:39] [Render thread/INFO]: [STDERR]: 	at dev.latvian.mods.kubejs.KubeJS.<init>(KubeJS.java:115)
[20:33:39] [Render thread/INFO]: [STDERR]: 	at dev.latvian.mods.kubejs.fabric.KubeJSFabric.onInitialize(KubeJSFabric.java:13)
[20:33:39] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
[20:33:39] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
[20:33:39] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
[20:33:39] [Render thread/INFO]: [STDERR]: 	at fudge.notenoughcrashes.fabric.mixinhandlers.ModLoaders.fabricEntrypoints(ModLoaders.java:9)
[20:33:39] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.redirect$jai000$catchFabricInit(class_310.java:34953)
[20:33:39] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.<init>(class_310.java:452)
[20:33:39] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:197)
[20:33:39] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
[20:33:39] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[20:33:39] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by MaxNeedsSnacks** [comment]
Can you reproduce this consistently? The error reads as if this was a one-off connection reset

**Comment by MaxNeedsSnacks** [comment]
See #26 for a workaround, if this keeps up we will likely have to find another way to go about remapping :/
